# SPDX-FileCopyrightText: 2025 German Aerospace Center, Gabriel Möring-Martínez
# SPDX-License-Identifier: MIT

data:
  input_path: inputs
  output_path: outputs

geography:
  countries:
    - Example Country
  use_clusters: true

powertrains:
  - BEV
  - Gasoline

model:
  first_stock_year: 2014
  end_year: 2040
  historical_validation: false

survival_rates:
  source: parameters
  grouping:
    - geo country
    - powertrain
  csp_available_years: 45
  files:
    parameters: csp_parameters.csv
